### ISSUE TITLE
[js-with-typescript-support] export of controller class breaks Prettier

### ISSUE THREAD

**Issue by piejanssens** [SAP-samples/ui5-cap-event-app#13]
```
["ERROR" - 9:00:55 AM] Error formatting document.
["ERROR" - 9:00:55 AM] Unexpected token, expected "{" (109:12)
  107 |       }
  108 |     }
> 109 |     export BaseController
      |            ^
  110 |   }
  111 | )
  112 |
```

**Comment by akudev** [comment]
Hi Pieter,
I'm not exactly sure how you got there. In the "js-with-typescript-support" branch you specified we have plain traditional UI5 JavaScript without ECMAScript modules. I'm not sure why you have an ES module export there.
There also is no "BaseController" class.
Also, Prettier is not used at all in this project.
Can you give a little more context? Maybe you applied the principles from this repo to something else?

Regards
Andreas
