### ISSUE TITLE
Event registration annotations reference i18n>Familienmitglieder

### ISSUE THREAD

**Issue by andrew-barnard** [SAP-samples/ui5-cap-event-app#2]
eventregistration-service-annotations.cds refers to i18n element Familienmitglieder. This element does not exist. Based upon i18n files, it should rather reference element Familymembers

**Comment by akudev** [comment]
Fixed by https://github.com/SAP-samples/ui5-cap-event-app/pull/3
Thanks for spotting this and sorry for the delay!
