### ISSUE TITLE
Changing name of "create" button in fiori elements app

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAP-samples/ui5-cap-event-app#8]
Hi,
First of all it's a wonderful app to learn SAP CAP, I have created the fiori elements app using wizard and consuming SAP CAP LOCAL SERVICE and i see two simple issues here.
1. When we click "create" to create new record and the new screen open to enter the data, but in the footer I see the button name "create", If I have to rename this button to "Save" I don't see there is any possibility to change the name?
2. After clicking on the "create" button and when data is saved, There is no button to go on main page where table is coming, Is there any possibility to somehow add a "back" button which takes me to main page?

**Comment by akudev** [comment]
Hi,
you are right, this is both a bit odd. Even when simply navigating to the details of an entry in the admin list, there doesn't seem to be a way to navigate back.

However, it is outside the scope of this sample project to report and fix issues within the Fiori Elements framework, sorry. We, the developers of this tutorial, are not developing that framework. If you are professionally working with Fiori Elements beyond this tutorial, I would recommend to open a regular ticket for that framework.

I [have updated](https://github.com/SAP-samples/ui5-cap-event-app/commit/6b7b5826235052bd0a8448c3c4e38e70c757bf02) the used UI5 version (thus also the Fiori Elements version), but the behavior has not changed.

Regards
Andreas
